### PR TITLE
feat: set smart detector alert rule name template

### PR DESCRIPTION
**Pull request by olepg**

### CODE REVIEW

**Review by sebastianlolv — DISMISSED** [review]
LGTM 👍

**Comment by hknutsen** [comment]
It might be possible for the user to provide a custom naming pattern instead. Will try to implement it.

**Comment by hknutsen** [comment]
Tests pass 🎉

**Comment by hknutsen** [comment]
Context:

- Smart detector alert rules are always created with a naming convention `<smart_detector_alert_rule_name> - <component_name>`.
- This PR adds a variable that allows the user to change the naming convention if needed.

**Comment by hknutsen** [comment]
Creating separate PR with more granular approach...

**Comment by hknutsen** [comment]
See alternative solution in #38.

**Comment by hknutsen** [comment]
#38 merged instead.

**Pull request closed without merging**
