### PR TITLE
feat!: migrate from smart detection rules to alert rules

### LINKED ISSUE #17: feat: migrate from smart detection rules to smart detection alert rules
## Description

Migrate from using [`azurerm_application_insights_smart_detection_rule`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_insights_smart_detection_rule) to [`azurerm_monitor_smart_detector_alert_rule`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_smart_detector_alert_rule).

This would require creating an action group outside of this module using [`azurerm_monitor_action_group`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_action_group).

A possible challenge is that we want to maintain a one-to-one mapping between module calls and visible resources in Azure, however all smart detection alert rules were recently made visible. Do we really want one module call per alert rule?

Seems like you can migrate using an ARM template by creating a resource of type `Microsoft.Insights/components/ProactiveDetectionConfigs` named `migrationToAlertRulesCompleted`, [ref](https://learn.microsoft.com/nb-no/azure/azure-monitor/alerts/alerts-smart-detections-migration#migrate-your-smart-detection-by-using-arm-templates).

## References

- [Migrate Azure Monitor Application Insights smart detection to alerts (preview)](https://learn.microsoft.com/nb-no/azure/azure-monitor/alerts/alerts-smart-detections-migration)

### PR DESCRIPTION
**Pull request by hknutsen**
BREAKING CHANGE: remove variable `smart_detection_rules` and add variable `action_group_id`.

Fixes #17

### CODE REVIEW

**Comment by hknutsen** [comment]
Tests pass :tada:

**Review by sebastianlolv — APPROVED** [review]
LGTM 👍

**Comment by sebastianlolv** [comment]
Tests pass 🥳

**Review by helenakallekleiv — APPROVED** [review]
Tests pass for me as well 🎉

**Pull request merged**
