### PR TITLE
docs: development and testing

### PR DESCRIPTION
**Pull request by hknutsen**

### CODE REVIEW

**Comment by hknutsen** [comment]
Test currently failing on creation of `azapi_update_resource.this` resource:

```
--- FAIL: TestBasicExample (195.99s)
    apply.go:15: 
                Error Trace:    apply.go:15
                                                        basic_example_test.go:16
                Error:          Received unexpected error:
                                FatalError{Underlying: error while running command: exit status 1; ╷
                                │ Error: checking for presence of existing Resource: (ResourceId "/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP_NAME>/providers/Microsoft.Insights/components/appi-0217cbcf9aef4175/ProactiveDetectionConfigs/migrationToAlertRulesCompleted" / Api Version "2018-05-01-preview"): ChainedTokenCredential authentication failed
                                │ GET http://169.254.169.254/metadata/identity/oauth2/token
                                │ --------------------------------------------------------------------------------
                                │ RESPONSE 403 connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: A socket operation was attempted to an unreachable network.
                                │ --------------------------------------------------------------------------------
                                │ connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: A socket operation was attempted to an unreachable network.
                                │ --------------------------------------------------------------------------------
                                │ 
                                │ 
                                │   with module.app_insights.azapi_resource.this,
                                │   on ../../main.tf line 88, in resource "azapi_resource" "this":
                                │   88: resource "azapi_resource" "this" {
                                │ 
                                ╵}
                Test:           TestBasicExample
```

**Comment by hknutsen** [comment]
Seems like AzApi provider is trying to use Managed Identity authentication for some reason. Will update dev container to automatically configure this provider for Azure CLI authentication.

**Comment by hknutsen** [comment]
Added the following to the dev container config:

```json
"containerEnv": {
  "ARM_USE_OIDC": "false",
  "ARM_USE_MSI": "false",
  "ARM_USE_CLI": "true"
}
```

**Comment by hknutsen** [comment]
Tests pass 🎉

**Review by kov117 — APPROVED** [review]
LGTM 👍🏽

**Pull request merged**
